spring:
  security:
    strategy: MODE_INHERITABLETHREADLOCAL

app:
  session:
    max-inactive-interval-duration: 1s
  jwt:
    rsa-private-key: |-
      -----BEGIN PRIVATE KEY-----
      MIIJQAIBADANBgkqhkiG9w0BAQEFAASCCSowggkmAgEAAoICAGOY6Q6YE46UKyBO
      ve7wuqBkkddIYmqSesNofGBnLlcQ9kt1aGWX/5LUQPSGyU8b/C5t77c/Iga1g/pe
      fep/2JguwmSjd0OxMqT0HXgO47W3v6dfIHaLr1LeQW3/0TwUHIPUfZXkxyqjF2mw
      3UxC755O91PXJ1msYuFFaiqW8HrYi28eUTao2Ot9VVUlzkEQJTbqQM3q2wa0i82p
      pmfHuYnGAU7A/ILkAgyTHu0hqAggjsdZ5IxwSqF7X8MIFc7kM8tVtVWOHuc4ambN
      TwxQDjQfWjGmE0ziyEvMgGrunorPtQK5NfNV9I1dOzSgptNoj1hBhnR2CNYNHLpU
      ClVzsVL91n2+XhlgX56l/VmCeXjpySRRYncDL64sKPWQrdnU+dcXagfZMfCbm/LO
      XhtqFbdYXm8tCkUxFrUIkqufNUbkJoAZ6dBRdibnQ8+rxyTQ/wm3p8nMsGonhoOX
      bAdkn+hwQ+AgzOJlVCdEzx7wbYnbqNA5Vo0Mi/7fZxOnuo/tRnc7MED9CWPVleDq
      m+cgXTWHxFXPalQAWXVSATDu8nuNxRyKFO0KFpneC7uBWgmbZboKjFojzEEgy9Qw
      9YikW6nbZmyq32ui2blqSK3cOQlCsQXmlhlDi1dPs1XrRzmPCngn4zNcShZPoXyV
      8fbib6VF+JU9KhC63i+Z73vzrLRpAgMBAAECggIASvrA6YW/o2UUmnvtLUb5mOpd
      iQ8rWEPyO84bZJAJKO7SHLjE4Ubu1uEIDY6zWuUcku+cuf3DZf2c4A3nCXU54EfD
      fPQ7QzDRibFlxg6fixxMInrQ+63pTZ+Y7nDaWjphxTVhXkkfT4/8fkryLwltT2bv
      d6TQMQhAYItbg7iiTjlbr0nJpjazJ4XxiequPfkjqxXrt5oJTiD55tjDN/n6SihQ
      r7NF5lw01rajX64ozAWGt7mK/9dBuBQjYbZihKD0BS3/F+uohDXKlJ4X1pMmPkMk
      KaB3gzhvxfCs9NOzc5kvEl/Qp+Kb+xinC9WuAhYDZFPgHykFOfAhIn1GUlKIuZts
      kI6fXJrbIJ8VWbl1bbZ2RQ+bmQr/V+eqxOCnhZ6bucP4I2gcXBly2CSOTqix7gnO
      PCx1N9krBHnrvVHNS/TbZ++8iG+kiV0mZyruZj2952LjeAYuak7d0DnJwWSylYIn
      czkdLsJzVS174Zph6faWfM3ZZ5QVrmhnh+UX6ZY4B7bEJX64nnbK0SMldzlKbp6S
      0oc5hTBjsmwskpRDap8/02bykahTrK+wo4zWYQQ0+ZoD0AHu/E87wrOo6MsVtnmZ
      ZAMe0nPhD5qzVoWX3Jq9T2JI/WYljMPlKkiLiFzTY4wWn5F9yqDs0Ge/SQwQkIX7
      1iSjosYQho3xfoB67iECggEBAKR4nYCgs6eu/pE64qJ0Sdy43VRLzG8+792Vt1sf
      IjOYTtlQyXUA5djD3Ro8vDKV681Ykd3ufZB8ZjA9PexY24s3JSXb65ANg+XQmY9v
      683LA8oc5l2/wMQOc5U4DgejIYTqh+4l9M+bIP5w7IfHmPBmnaszWHWGJFsqCLAY
      WB1nkUqvcLG4UTRGCjF89Efux5piFDzDoV8tdEnw2Mm3rWlDCtlXyRhuarOD5nJC
      XCEsAUXp79OSUXk9TTT2/q6rM+1cpaVbNOXrk3DWa6vHJJAzHeJ0Z5mvJiwZFVvo
      u91YUkqBj06vJOaKjrI62PRRKwrCEA7AmyRjDOdTgooIMeUCggEBAJsGCrBedWPj
      IoN0mTr+Lu/8eCWhLjD6w2WhV9LYennIw7zekBIQ6Zs34XI4nxL3u7VhzEavatyf
      AsN0CQ+hudyrQTN6ffy7NFe9Q0h3t/gGqF8eY1OCpfplsFoRi86EKNOEfJFVVMzj
      dalfilMgxCNN9/ZzNS8g0manHnk867QXpwxeAapU4AhyOC1tePLX98548h+OIeAw
      cPvIP6aC5x4Xr+Eg98NDWim5g0cEQyXI3lmS6U2LNe3aVaHo/jplOhDyzcubM7RE
      hae9fQOM36FECpMxRaj5HpEAXWZ7rYrdbhrDSJYPmuabaRuZZFVy5QBhsy6MSfZ5
      veOkaKXq4DUCggEAft4PWF4d1tYUxgAvO/MJ2rm6+MAzZQieTEWllyNv5W6yO82m
      aJuVsNx83DVHUpn0t4R/mDrUHrTmuoUzE/IC/+M8w3Rdw9O5D3gWS9+gfDECrlAW
      nvBACLvBCrSfleKPA5FJ4zjiG5ZlIAAJZD9hyObO7nV/4b/koXHOG8/bgGsYVwz3
      mA8+jF0Oldf2MtqMm5jWVXzuKJXOYw7mmssVd+HgJ4EgvLjHk8vF4hMwL+Ja5Qws
      E/6E3EmeGaIBGMk1F/5kRCYTqttJ8zti+LF3kcfsYHc8Rv8lKdT7ddcTuwzbBV/l
      JGPTygXNRsw/+E34Lqc9bbPCuJGzLWlsg38IxQKCAQAvvnScTPsqgFGo2sg2ewJJ
      tx/ptvJa82AqdL5vmWxfBY4DJSiJ59uKinNMklOrq9CL1Ertmij3OaHIQHxp7A0q
      ATRbfmY+6Aj+3LNUJkrqgGJqqRk+JwanT5o4ox7Dw8AvJKaYvAcZ8xPRzjLz1yuR
      E/pCVMkUcq9aHi4seK6/EGnKTUmGBA3bjBHxK74MTKdtV6J6RXP5b/HcGZhA2CAG
      DJWGaHjmEmA6aYAc5xsnD+4q+CwSTcWWM6Ab9X4WzgZMIftvsaUC5/eh6aIO7dwR
      9rqrConBuLfJQKuDXKPeGMRIScyZKsUyMLr2XQ+hoXkV3QEqXNqKpoPtED2KnAPh
      AoIBABdxf8LJgCP46UQdDanTKT3rkpZD3Vag/9s887FUiQ0mnXYBvA8BA6BKZ5rT
      07xQi89KhXqfO0aBkzTbwu3J+61Alf4gikmQzAZbNeadQ9Wu6baqt1YzpI3VBuYj
      ZEiC+Dt4Ha7acw/I6Y+iW/hWYKrIKWAEpJfDliywhsnbNSVD6f/ZLNkxAgAhakOH
      tq8Dfv+j5DlfPMlLaN2RRNIqzjALtOnfsnq/O/jIKyVuRauC7W8NzAg6wTNHgJQK
      1R0FSwRyDdmbfzDbGHIZxG5vpfgvCx87fAud66+G4RvN/0EDCZEMhEAuZnChQXRi
      1BEkYZrcrJp9rKC5s83bTJjIvBk=
      -----END PRIVATE KEY-----
    rsa-public-key: |-
      -----BEGIN PUBLIC KEY-----
      MIICITANBgkqhkiG9w0BAQEFAAOCAg4AMIICCQKCAgBjmOkOmBOOlCsgTr3u8Lqg
      ZJHXSGJqknrDaHxgZy5XEPZLdWhll/+S1ED0hslPG/wube+3PyIGtYP6Xn3qf9iY
      LsJko3dDsTKk9B14DuO1t7+nXyB2i69S3kFt/9E8FByD1H2V5McqoxdpsN1MQu+e
      TvdT1ydZrGLhRWoqlvB62ItvHlE2qNjrfVVVJc5BECU26kDN6tsGtIvNqaZnx7mJ
      xgFOwPyC5AIMkx7tIagIII7HWeSMcEqhe1/DCBXO5DPLVbVVjh7nOGpmzU8MUA40
      H1oxphNM4shLzIBq7p6Kz7UCuTXzVfSNXTs0oKbTaI9YQYZ0dgjWDRy6VApVc7FS
      /dZ9vl4ZYF+epf1Zgnl46ckkUWJ3Ay+uLCj1kK3Z1PnXF2oH2THwm5vyzl4bahW3
      WF5vLQpFMRa1CJKrnzVG5CaAGenQUXYm50PPq8ck0P8Jt6fJzLBqJ4aDl2wHZJ/o
      cEPgIMziZVQnRM8e8G2J26jQOVaNDIv+32cTp7qP7UZ3OzBA/Qlj1ZXg6pvnIF01
      h8RVz2pUAFl1UgEw7vJ7jcUcihTtChaZ3gu7gVoJm2W6CoxaI8xBIMvUMPWIpFup
      22Zsqt9rotm5akit3DkJQrEF5pYZQ4tXT7NV60c5jwp4J+MzXEoWT6F8lfH24m+l
      RfiVPSoQut4vme9786y0aQIDAQAB
      -----END PUBLIC KEY-----

    # Generated with `openssl rand -base64 172 | tr -d '\n'`
    secret: |-
      5E9Q6Jc/JKyOosMs7D/dcpac2yFnka94FW3PFlGaiu6ganGDHuRx3LJiOFMB+PIwzvM5XECcFn16LzB+cjWWWhXgwGNh8YPnSYRJPXpY84M2JlvjxjnOxQSlsv7VGYGp/zySnCH6tHtJaB/cOv0xjfgo7p7UuCxKHambVQ8DW5N7yn9MY2vo+1ias/bHYiKiuS1AS4zYdZd0zAXDNv7SwUriG7nu1Gp4dDQvnA==
logging:
  level:
    org.springframework.security: DEBUG

debug:
  true